//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyberjax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyberjax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlphaEffect {
            get {
                object obj = ResourceManager.GetObject("AlphaEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brush.
        /// </summary>
        internal static string BrushEffectName {
            get {
                return ResourceManager.GetString("BrushEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BulgeEffect {
            get {
                object obj = ResourceManager.GetObject("BulgeEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ColorAngleEffect {
            get {
                object obj = ResourceManager.GetObject("ColorAngleEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Mask.
        /// </summary>
        internal static string ColorMaskEffectName {
            get {
                return ResourceManager.GetString("ColorMaskEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Transparency.
        /// </summary>
        internal static string ColorTransparencyEffectName {
            get {
                return ResourceManager.GetString("ColorTransparencyEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distortion Effect.
        /// </summary>
        internal static string DistortionEffectName {
            get {
                return ResourceManager.GetString("DistortionEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual Distortion Effect.
        /// </summary>
        internal static string DualDistortionEffectName {
            get {
                return ResourceManager.GetString("DualDistortionEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyberjax.
        /// </summary>
        internal static string EffectSubMenuName {
            get {
                return ResourceManager.GetString("EffectSubMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elliptical Bulge Effect.
        /// </summary>
        internal static string EllipticalBulgeEffectName {
            get {
                return ResourceManager.GetString("EllipticalBulgeEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Alpha Channel.
        /// </summary>
        internal static string ExtractAlphaEffectName {
            get {
                return ResourceManager.GetString("ExtractAlphaEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Gaussian Blur.
        /// </summary>
        internal static string FastGaussianBlurEffectName {
            get {
                return ResourceManager.GetString("FastGaussianBlurEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Brightness Graph.
        /// </summary>
        internal static string HueBrightnessEffectName {
            get {
                return ResourceManager.GetString("HueBrightnessEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HueSaturation {
            get {
                object obj = ResourceManager.GetObject("HueSaturation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Sat Bright Graph.
        /// </summary>
        internal static string HueSaturationBrightnessEffectName {
            get {
                return ResourceManager.GetString("HueSaturationBrightnessEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue Saturation Graph.
        /// </summary>
        internal static string HueSaturationEffectName {
            get {
                return ResourceManager.GetString("HueSaturationEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineEffect {
            get {
                object obj = ResourceManager.GetObject("LineEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Line.
        /// </summary>
        internal static string LineEffectName {
            get {
                return ResourceManager.GetString("LineEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 0.
        /// </summary>
        internal static string LineEffectOffset0Text {
            get {
                return ResourceManager.GetString("LineEffectOffset0Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 1.
        /// </summary>
        internal static string LineEffectOffset1Text {
            get {
                return ResourceManager.GetString("LineEffectOffset1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaskEffect {
            get {
                object obj = ResourceManager.GetObject("MaskEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaskEffect2 {
            get {
                object obj = ResourceManager.GetObject("MaskEffect2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaskEffect3 {
            get {
                object obj = ResourceManager.GetObject("MaskEffect3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PerformanceEffect {
            get {
                object obj = ResourceManager.GetObject("PerformanceEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performace.
        /// </summary>
        internal static string PerformanceEffectName {
            get {
                return ResourceManager.GetString("PerformanceEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ReplaceTransColorEffect {
            get {
                object obj = ResourceManager.GetObject("ReplaceTransColorEffect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Transparency Color.
        /// </summary>
        internal static string ReplaceTransColorEffectName {
            get {
                return ResourceManager.GetString("ReplaceTransColorEffectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResetIcon {
            get {
                object obj = ResourceManager.GetObject("ResetIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
